UPDATE Product SET UnitOfMeasure = '3KG' WHERE NAME LIKE '%(3KG)%'

UPDATE [pricelist.template].[63] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE NAME LIKE '%(3KG)%'
UPDATE [pricelist.template].[64] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE NAME LIKE '%(3KG)%'
UPDATE [pricelist.template].[68] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE NAME LIKE '%(3KG)%'

UPDATE  [pricelist.template].[1] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[2] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[3] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[4] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[5] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[6] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[7] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[8] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[10] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[11] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[12] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[13] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[14] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[15] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[16] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[17] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[18] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[19] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[20] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[21] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[22] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[23] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[24] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[25] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[26] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[27] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[28] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[29] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[30] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE  [pricelist.template].[31] SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'

UPDATE   [pricelist.template].[33]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[34]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[35]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[36]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[37]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[38]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[39]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[40]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[41]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[42]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[43]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[44]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[47]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[48]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[51]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[52]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[53]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[55]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[56]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[57]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[58]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[60]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[61]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10065]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10066]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10067]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10068]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10069]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10070]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10071]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10072]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10073]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10074]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10075]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10076]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10077]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10078]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10079]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10080]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10081]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10082]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10083]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10084]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10085]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10086]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10087]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10088]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10089]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10090]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10091]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10092]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10093]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10094]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10095]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10096]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10097]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10098]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10099]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10100]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10101]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10102]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10103]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10104]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10105]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10106]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10107]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10108]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10109]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10110]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10111]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10112]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10113]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10114]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10115]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10116]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10117]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10118]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10119]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10120]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10121]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10122]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10123]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10124]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10125]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10126]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10127]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10128]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10129]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10130]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10131]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10132]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10133]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10134]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10135]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10136]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10137]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10138]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10139]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10140]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10141]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10142]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10143]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10144]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10145]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10146]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10147]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10148]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10149]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10150]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10151]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10152]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10153]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10154]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10155]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10156]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10157]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10158]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10159]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10160]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10161]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10162]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10163]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10164]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10165]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10166]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10167]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10168]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10169]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10170]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10171]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10172]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10173]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10174]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10175]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10176]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10177]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10178]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10179]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10180]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10181]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10182]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10183]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10184]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10185]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10186]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10187]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10188]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10189]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10190]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10191]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10192]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10193]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10194]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10195]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10196]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10197]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10198]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10199]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10200]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[10201]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20199]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20200]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20201]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20202]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20203]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20204]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20205]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20206]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20207]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20208]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20209]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20210]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20211]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20212]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20213]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20214]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20215]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20216]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20217]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20218]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20219]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20220]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20221]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20222]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20223]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20224]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20225]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20226]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'
UPDATE   [pricelist.template].[20227]	SET UnitOfMeasure = '3KG', PurchaseUnitOfMeasure = '3KG' WHERE  NAME LIKE '%(3KG)%'

UPDATE [sale.order.detail].[1]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[2]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[3]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[4]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[5]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[6]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[7]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[8]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[10]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[11]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[12]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[14]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[15]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[16]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[17]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[18]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[20]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[22]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[23]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[27]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[28]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[29]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[31]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[32]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[33]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[34]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[37]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[38]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[39]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[40]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[42]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[43]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[44]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[45]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[47]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[48]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[49]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[51]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[52]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[53]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[54]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[56]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[57]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[59]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[60]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[61]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[63]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[65]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[67]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[68]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[69]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[70]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[71]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[72]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[73]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[74]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[75]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[76]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[77]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[78]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[79]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[80]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[81]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[82]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[83]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[84]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[85]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[87]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[91]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[93]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[94]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[95]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[98]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[99]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[100]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[101]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[102]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[103]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[104]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[105]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[107]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[108]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[110]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[112]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[113]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[114]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[116]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[118]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[119]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[120]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[121]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[126]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[127]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[128]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[129]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[130]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[131]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[132]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[135]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[136]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[137]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[138]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[140]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[141]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[142]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[143]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[144]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[145]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[146]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[148]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[149]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[150]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[151]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[152]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[157]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[158]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[161]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[163]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[164]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[165]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[166]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[167]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[168]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[170]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[173]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[174]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[175]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[176]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[177]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[178]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[180]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[181]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[183]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[185]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[186]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[188]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[191]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[192]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[194]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[195]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[196]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[197]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[198]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[200]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[203]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[206]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[207]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[208]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[210]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[211]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[212]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[215]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[217]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[220]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[223]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[224]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[225]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[227]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[228]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[230]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[231]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[234]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[235]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[236]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[237]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[240]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[246]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[247]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[248]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[250]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[251]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[252]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[253]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[254]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[255]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[256]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[257]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[260]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[263]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[266]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[269]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[272]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[274]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[276]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[279]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[284]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[285]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[286]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[287]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[291]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[297]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[299]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[301]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[302]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[303]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[304]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[306]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[309]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[311]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[312]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[313]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[314]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[315]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[316]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[318]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[319]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[320]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[322]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[324]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[326]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[328]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[329]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[330]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[331]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[335]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[336]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[338]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[339]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[343]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[344]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[20347]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[20348]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[20349]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[20350]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[20351]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[20352]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30351]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30352]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30353]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30354]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30355]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30356]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30357]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30358]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30359]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30360]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30361]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30362]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30363]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30364]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30365]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30366]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30367]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30368]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30369]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30370]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30371]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30372]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30373]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30374]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30375]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30376]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30377]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30378]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30379]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30380]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30381]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30382]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30383]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30384]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30385]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30386]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30387]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30388]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30389]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30390]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30391]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'
UPDATE [sale.order.detail].[30392]	SET ProductUnitOfMeasure = '3KG' WHERE ProductName LIKE '%(3KG)%'

UPDATE [sale.order.detail].[FC2J] SET UnitOfMeasure = '3KG' WHERE NAME LIKE '%(3KG)%'
UPDATE [sale.order.detail].[Payment_FC2J] SET UnitOfMeasure = '3KG' WHERE NAME LIKE '%(3KG)%'
